name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.arch }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64/v8
        os:
          - ubuntu-24.04
          - ubuntu-22.04
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup-podman
        uses: ./

      - name: test-podman
        working-directory: ${{ runner.temp }}
        run: |
          podman info

          curl -f -L --retry 5 https://github.com/tweag/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1

          podman build \
            --arch ${{ matrix.arch }} \
            --network host \
            --pull \
            --squash-all \
            --tag rust:alpine-mimalloc \
            .

          podman run \
            --arch ${{ matrix.arch }} \
            --init \
            --network host \
            --rm \
            --tmpfs /tmp:exec \
            --volume $PWD:/workspace \
            --workdir /workspace \
            rust:alpine-mimalloc \
            /workspace/test.sh
          MIMALLOC_VERBOSE=1 ./bin/names
          file ./bin/names
